// Datos de prueba para el dashboard NPS de mentores
export const mockNpsData = {
  mentorId: '31a57e7b-db0f-421f-aea0-bf985e00de58',
  mentorName: 'Héctor Chocobar Torrejón',
  overall: {
    teacherAverage: 9.0,
    totalEvaluations: 45,
  },
  totalCohorts: 10,
  activeCohorts: 1,
  pastCohorts: 9,
  visualizationData: {
    kpis: {
      overallTeacherAverage: 9.0,
      overallCohortAverage: 8.45,
      totalEvaluations: 45,
      totalCohorts: 10,
      activeCohorts: 1,
      finishedCohorts: 9,
      averageParticipation: 79.2,
    },
    cohorts: [
      {
        id: 'cohort-1',
        name: 'Cohorte A - Full Stack',
        status: 'Active',
        isActive: true,
        metrics: {
          teacher: { average: 9.2, nps: 0, totalEvaluations: 5 },
          cohort: { average: 8.8, nps: 0, totalEvaluations: 5 },
          participation: { average: 0.85, totalEvaluations: 5 },
        },
        progression: {
          teacher: [
            { date: '4507', score: 9.0, evaluationId: '4507' },
            { date: '5163', score: 9.2, evaluationId: '5163' },
            { date: '5982', score: 9.5, evaluationId: '5982' },
            { date: '6123', score: 9.1, evaluationId: '6123' },
            { date: '6456', score: 9.4, evaluationId: '6456' },
          ],
          cohort: [
            { date: '4507', score: 8.5, evaluationId: '4507' },
            { date: '5163', score: 8.8, evaluationId: '5163' },
            { date: '5982', score: 9.0, evaluationId: '5982' },
            { date: '6123', score: 8.9, evaluationId: '6123' },
            { date: '6456', score: 8.9, evaluationId: '6456' },
          ],
          participation: [
            { date: '4507', score: 0.8, evaluationId: '4507' },
            { date: '5163', score: 0.85, evaluationId: '5163' },
            { date: '5982', score: 0.9, evaluationId: '5982' },
            { date: '6123', score: 0.85, evaluationId: '6123' },
            { date: '6456', score: 0.85, evaluationId: '6456' },
          ],
        },
        evaluations: [],
        totalEvaluations: 5,
      },
      {
        id: 'cohort-2',
        name: 'Cohorte B - Python',
        status: 'Final Project',
        isActive: false,
        metrics: {
          teacher: { average: 8.8, nps: 0, totalEvaluations: 4 },
          cohort: { average: 8.2, nps: 0, totalEvaluations: 4 },
          participation: { average: 0.75, totalEvaluations: 4 },
        },
        progression: {
          teacher: [
            { date: '4001', score: 8.5, evaluationId: '4001' },
            { date: '4123', score: 8.8, evaluationId: '4123' },
            { date: '4256', score: 9.0, evaluationId: '4256' },
            { date: '4389', score: 8.9, evaluationId: '4389' },
          ],
          cohort: [
            { date: '4001', score: 7.8, evaluationId: '4001' },
            { date: '4123', score: 8.2, evaluationId: '4123' },
            { date: '4256', score: 8.5, evaluationId: '4256' },
            { date: '4389', score: 8.3, evaluationId: '4389' },
          ],
          participation: [
            { date: '4001', score: 0.7, evaluationId: '4001' },
            { date: '4123', score: 0.75, evaluationId: '4123' },
            { date: '4256', score: 0.8, evaluationId: '4256' },
            { date: '4389', score: 0.75, evaluationId: '4389' },
          ],
        },
        evaluations: [],
        totalEvaluations: 4,
      },
      {
        id: 'cohort-3',
        name: 'Cohorte C - React',
        status: 'Finished',
        isActive: false,
        metrics: {
          teacher: { average: 9.5, nps: 0, totalEvaluations: 6 },
          cohort: { average: 8.9, nps: 0, totalEvaluations: 6 },
          participation: { average: 0.9, totalEvaluations: 6 },
        },
        progression: {
          teacher: [
            { date: '3501', score: 9.2, evaluationId: '3501' },
            { date: '3623', score: 9.4, evaluationId: '3623' },
            { date: '3745', score: 9.6, evaluationId: '3745' },
            { date: '3867', score: 9.5, evaluationId: '3867' },
            { date: '3989', score: 9.7, evaluationId: '3989' },
            { date: '4111', score: 9.6, evaluationId: '4111' },
          ],
          cohort: [
            { date: '3501', score: 8.7, evaluationId: '3501' },
            { date: '3623', score: 8.9, evaluationId: '3623' },
            { date: '3745', score: 9.1, evaluationId: '3745' },
            { date: '3867', score: 9.0, evaluationId: '3867' },
            { date: '3989', score: 9.2, evaluationId: '3989' },
            { date: '4111', score: 9.1, evaluationId: '4111' },
          ],
          participation: [
            { date: '3501', score: 0.85, evaluationId: '3501' },
            { date: '3623', score: 0.9, evaluationId: '3623' },
            { date: '3745', score: 0.92, evaluationId: '3745' },
            { date: '3867', score: 0.9, evaluationId: '3867' },
            { date: '3989', score: 0.93, evaluationId: '3989' },
            { date: '4111', score: 0.91, evaluationId: '4111' },
          ],
        },
        evaluations: [],
        totalEvaluations: 6,
      },
      {
        id: 'cohort-4',
        name: 'Cohorte D - Java',
        status: 'Finished',
        isActive: false,
        metrics: {
          teacher: { average: 8.6, nps: 0, totalEvaluations: 4 },
          cohort: { average: 8.1, nps: 0, totalEvaluations: 4 },
          participation: { average: 0.7, totalEvaluations: 4 },
        },
        progression: {
          teacher: [
            { date: '3001', score: 8.3, evaluationId: '3001' },
            { date: '3123', score: 8.6, evaluationId: '3123' },
            { date: '3245', score: 8.8, evaluationId: '3245' },
            { date: '3367', score: 8.7, evaluationId: '3367' },
          ],
          cohort: [
            { date: '3001', score: 7.8, evaluationId: '3001' },
            { date: '3123', score: 8.1, evaluationId: '3123' },
            { date: '3245', score: 8.3, evaluationId: '3245' },
            { date: '3367', score: 8.2, evaluationId: '3367' },
          ],
          participation: [
            { date: '3001', score: 0.65, evaluationId: '3001' },
            { date: '3123', score: 0.7, evaluationId: '3123' },
            { date: '3245', score: 0.72, evaluationId: '3245' },
            { date: '3367', score: 0.73, evaluationId: '3367' },
          ],
        },
        evaluations: [],
        totalEvaluations: 4,
      },
      {
        id: 'cohort-5',
        name: 'Cohorte E - Data Science',
        status: 'Finished',
        isActive: false,
        metrics: {
          teacher: { average: 9.1, nps: 0, totalEvaluations: 5 },
          cohort: { average: 8.7, nps: 0, totalEvaluations: 5 },
          participation: { average: 0.82, totalEvaluations: 5 },
        },
        progression: {
          teacher: [
            { date: '2501', score: 8.8, evaluationId: '2501' },
            { date: '2623', score: 9.0, evaluationId: '2623' },
            { date: '2745', score: 9.2, evaluationId: '2745' },
            { date: '2867', score: 9.1, evaluationId: '2867' },
            { date: '2989', score: 9.3, evaluationId: '2989' },
          ],
          cohort: [
            { date: '2501', score: 8.4, evaluationId: '2501' },
            { date: '2623', score: 8.6, evaluationId: '2623' },
            { date: '2745', score: 8.8, evaluationId: '2745' },
            { date: '2867', score: 8.7, evaluationId: '2867' },
            { date: '2989', score: 8.9, evaluationId: '2989' },
          ],
          participation: [
            { date: '2501', score: 0.78, evaluationId: '2501' },
            { date: '2623', score: 0.8, evaluationId: '2623' },
            { date: '2745', score: 0.83, evaluationId: '2745' },
            { date: '2867', score: 0.82, evaluationId: '2867' },
            { date: '2989', score: 0.85, evaluationId: '2989' },
          ],
        },
        evaluations: [],
        totalEvaluations: 5,
      },
    ],
    charts: {
      averagesByCohort: [
        {
          cohortName: 'Cohorte A - Full Stack',
          teacherAverage: 9.2,
          cohortAverage: 8.8,
          participation: 0.85,
          totalEvaluations: 5,
        },
        {
          cohortName: 'Cohorte B - Python',
          teacherAverage: 8.8,
          cohortAverage: 8.2,
          participation: 0.75,
          totalEvaluations: 4,
        },
        {
          cohortName: 'Cohorte C - React',
          teacherAverage: 9.5,
          cohortAverage: 8.9,
          participation: 0.9,
          totalEvaluations: 6,
        },
        {
          cohortName: 'Cohorte D - Java',
          teacherAverage: 8.6,
          cohortAverage: 8.1,
          participation: 0.7,
          totalEvaluations: 4,
        },
        {
          cohortName: 'Cohorte E - Data Science',
          teacherAverage: 9.1,
          cohortAverage: 8.7,
          participation: 0.82,
          totalEvaluations: 5,
        },
      ],
      participationByCohort: [
        { cohortName: 'Cohorte A - Full Stack', participation: 85 },
        { cohortName: 'Cohorte B - Python', participation: 75 },
        { cohortName: 'Cohorte C - React', participation: 90 },
        { cohortName: 'Cohorte D - Java', participation: 70 },
        { cohortName: 'Cohorte E - Data Science', participation: 82 },
      ],
    },
    tables: {
      cohorts: [
        {
          id: 'cohort-1',
          name: 'Cohorte A - Full Stack',
          status: 'Active',
          teacherAverage: 9.2,
          cohortAverage: 8.8,
          participation: 85,
          totalEvaluations: 5,
        },
        {
          id: 'cohort-2',
          name: 'Cohorte B - Python',
          status: 'Final Project',
          teacherAverage: 8.8,
          cohortAverage: 8.2,
          participation: 75,
          totalEvaluations: 4,
        },
        {
          id: 'cohort-3',
          name: 'Cohorte C - React',
          status: 'Finished',
          teacherAverage: 9.5,
          cohortAverage: 8.9,
          participation: 90,
          totalEvaluations: 6,
        },
        {
          id: 'cohort-4',
          name: 'Cohorte D - Java',
          status: 'Finished',
          teacherAverage: 8.6,
          cohortAverage: 8.1,
          participation: 70,
          totalEvaluations: 4,
        },
        {
          id: 'cohort-5',
          name: 'Cohorte E - Data Science',
          status: 'Finished',
          teacherAverage: 9.1,
          cohortAverage: 8.7,
          participation: 82,
          totalEvaluations: 5,
        },
      ],
      recentEvaluations: [
        {
          date: '6456',
          score: 9.4,
          cohortName: 'Cohorte A - Full Stack',
          status: 'Completada',
        },
        {
          date: '6123',
          score: 9.1,
          cohortName: 'Cohorte A - Full Stack',
          status: 'Completada',
        },
        {
          date: '5982',
          score: 9.5,
          cohortName: 'Cohorte A - Full Stack',
          status: 'Completada',
        },
        {
          date: '5163',
          score: 9.2,
          cohortName: 'Cohorte A - Full Stack',
          status: 'Completada',
        },
        {
          date: '4507',
          score: 9.0,
          cohortName: 'Cohorte A - Full Stack',
          status: 'Completada',
        },
        {
          date: '4389',
          score: 8.9,
          cohortName: 'Cohorte B - Python',
          status: 'Completada',
        },
        {
          date: '4256',
          score: 9.0,
          cohortName: 'Cohorte B - Python',
          status: 'Completada',
        },
        {
          date: '4123',
          score: 8.8,
          cohortName: 'Cohorte B - Python',
          status: 'Completada',
        },
        {
          date: '4001',
          score: 8.5,
          cohortName: 'Cohorte B - Python',
          status: 'Completada',
        },
        {
          date: '4111',
          score: 9.6,
          cohortName: 'Cohorte C - React',
          status: 'Completada',
        },
      ],
    },
  },
}
